### ISSUE TITLE
Yo! Para di makalimutan ung mga request ko.

### ISSUE THREAD

**Issue by MarceloAnzano** [justindbms/evaluation-system#7]
Search users:
-Kelangan ba talaga whole name?
-Pahingi rin ng string examples ng search.

Percentage:
-Sana nakadisplay na ung current percentage sa bawat input para madaling ienter kapag onti lang babaguhin.

Ratings (Principal)
-Ratings na detailed
-Ratings na makikita kung sino nagrate ng ganun

User create
-users  csv

Principal page
-Ung principal settings na parang admin page kaso di kasama ung iba.

**SOFT ENGG at OCR muna tayo**

**Comment by justindbms** [comment]
Search Users:
- whole name lang talaga. ayoko gawan ng substring search.

Percentage:
-low priority, pag may time nalang

Ratings:
- wip
- wip

User Create:
- depende pa to.

principal page:
- kinonnect ko na siya sa admin_index.php haha

may few concerns ako sa front-end:
- lalagyan ko ng parang select sa create section. pag selected == existing section sa db. ilalabas yung current subj. pag selected == 'new section', mag-eenable yung mga input box for grade/section
- nagdodoble ang entries sa create section sa admin page. (di ko pa napupush, wait ka lang)
- gawan mo ng disabled input something yung sa admin/manage page. yung parang sa create users.

wait for the new push nalang muna.

**Comment by justindbms** [comment]
Other notes:
- Di ko pa alam kung san ilalagay ang final ratings ng archived lol
- WIP yung export final ratings
